[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "github_conn"
version = "0.1.0"
authors = [
  { name="Alessandro", email="gargoalexdc@gmail.com" },
]
description = "Un pacchetto semplice per connettersi alle API di GitHub"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.28.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Dal-Canto/github_conn"
